version: "3.9"

services:
  db:
    image: postgres:14
    container_name: event_hall_db
    restart: always
    environment:
      POSTGRES_DB: event_hall_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: event_hall_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://your_db_user:your_db_password@db:5432/event_hall_db

  nginx:
    image: nginx:latest
    container_name: event_hall_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
